import { AxiosRequestConfig } from 'axios';
import { Logger } from '@map-colonies/js-logger';
import { Layer3DRecordInput } from '../../AUTOGENERATED/GraphQLClass';
import { IngestionData } from '../../graphql/inputTypes';
import { absolutePathToNfs } from '../../helpers/string';
import { requestHandler } from '../../utils';
import { IConfig } from '../interfaces';
import { IIngestionManagerService } from './ingestion-manager.interface';

export class IngestionManager3D implements IIngestionManagerService {
  private readonly serviceURL: string = '';

  public constructor(private readonly config: IConfig, private readonly logger: Logger) {
    this.serviceURL = this.config.get('ingestionServices.3d.url');
  }

  public async ingest(data: IngestionData): Promise<IngestionData> {
    await requestHandler(`${this.serviceURL}/models`, 'POST', this.buildPayload(data));
    return data;
  }

  private buildPayload(data: IngestionData): AxiosRequestConfig {
    const metadata = data.metadata as Layer3DRecordInput;
    const payloadData = {
      modelPath: absolutePathToNfs(data.directory),
      tilesetFilename: data.fileNames[0],
      metadata: {
        ...metadata,
        producerName: 'IDFMU',
        srsId: Number(metadata.srsId),
        productVersion: Number(metadata.productVersion),
      },
    };

    this.logger.info(`[IngestionManager3D][buildPayload] generated payload: ${JSON.stringify(payloadData)}.`);

    return {
      data: {
        ...payloadData,
      },
    };
  }
}
