import { ObjectType, Field, registerEnumType } from 'type-graphql';
import { FieldCategory } from '@map-colonies/mc-model-types';
import { GraphQLScalarType } from 'graphql';

// eslint-disable-next-line import/exports-last
export enum AutocomplitionType {
  DOMAIN = 'domain',
  SERVICE = 'service',
}
registerEnumType(AutocomplitionType, { name: 'AutocomplitionType' });

// eslint-disable-next-line import/exports-last
export enum ValidationType {
  VALUE = 'value',
  FIELD = 'field',
  REQUIRED = 'required',
}
registerEnumType(ValidationType, { name: 'ValidationType' });

registerEnumType(FieldCategory, { name: 'FieldCategory' });
export const enumDictionary = new GraphQLScalarType({ name: 'enumDictionary' });

@ObjectType()
export class EnumDictionary {
  @Field({ nullable: false })
  public displayKey: string;

  @Field({ nullable: true })
  public tooltipKey?: string;

  @Field({ nullable: true })
  public icon?: string;
}

@ObjectType()
export class EnumAspects {
  @Field((type) => enumDictionary, { nullable: false })
  public dictionary: Record<string, EnumDictionary>;
}

@ObjectType()
export class Autocompletion {
  @Field((type) => AutocomplitionType, { nullable: false })
  public type: AutocomplitionType;

  @Field({ nullable: false })
  public value: string;
}

@ObjectType()
export class ValidationConfig {
  @Field({ nullable: false })
  public errorMsgCode: string;

  @Field((type) => ValidationType, { nullable: false })
  public type: ValidationType;

  @Field({ nullable: true })
  public min?: string; //number | string | '$NOW';

  @Field({ nullable: true })
  public max?: string; //number | string;

  @Field({ nullable: true })
  public minLength?: number;

  @Field({ nullable: true })
  public maxLength?: number;

  @Field({ nullable: true })
  public pattern?: string;

  @Field({ nullable: true })
  public errorMsgTranslation: string;
}

@ObjectType()
export class FieldConfig {
  @Field({ nullable: false })
  public fieldName: string;

  @Field({ nullable: false })
  public label: string;

  @Field({ nullable: true })
  public fullWidth?: boolean;

  @Field({ nullable: true })
  public isManuallyEditable?: boolean; // is field might be edited after creation

  @Field({ nullable: true })
  public isFilterable?: boolean; // is field might participate in filter/search params

  @Field({ nullable: true })
  public isSortable?: boolean; // is field might participate in sorting

  @Field({ nullable: true })
  public isRequired?: boolean; // is field mandatory

  @Field({ nullable: true })
  public isAutoGenerated?: boolean; // is field auto-generated

  @Field({ nullable: true })
  public isCreationEssential?: boolean; // // is field should participate in entity creation

  @Field((type) => Autocompletion, { nullable: true })
  public autocomplete?: Autocompletion;

  @Field((type) => [String], { nullable: true })
  public infoMsgCode?: string[];

  @Field((type) => [ValidationConfig], { nullable: true })
  public validation?: ValidationConfig[];

  @Field((type) => EnumAspects, { nullable: true })
  public enumValues?: EnumAspects;

  @Field((type) => [FieldConfig], { nullable: true })
  public subFields?: FieldConfig[];
}

@ObjectType()
export class CategoryConfig {
  @Field((type) => FieldCategory, { nullable: false })
  public category: FieldCategory;

  @Field({ nullable: false })
  public categoryTitle: string;

  @Field((type) => [FieldConfig], { nullable: false })
  public fields: FieldConfig[];
}

@ObjectType()
export class EntityDescriptor {
  @Field({ nullable: false })
  public type: string;

  @Field((type) => [CategoryConfig], { nullable: false })
  public categories: CategoryConfig[];
}
